Removing a misplaced exit(0); Also enabling maintainer mode.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -680,6 +680,9 @@ am__leading_dot
 AMTAR
 am__tar
 am__untar
+MAINTAINER_MODE_TRUE
+MAINTAINER_MODE_FALSE
+MAINT
 CC
 CFLAGS
 LDFLAGS
@@ -1338,7 +1341,8 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
-  --enable-optimize       Build with full optimization [default=no]
+  --enable-maintainer-mode  enable make rules and dependencies not useful
+			  (and sometimes confusing) to the casual installer
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
 
@@ -2368,24 +2372,27 @@ am__tar='${AMTAR} chof - "$$tardir"'; am__untar='${AMTAR} xf -'
 
 
 
-# AM_MAINTAINER_MODE
-
-# enable full optimization by configure switch
-# Check whether --enable-optimize was given.
-if test "${enable_optimize+set}" = set; then
-  enableval=$enable_optimize;  case "${enableval}" in
-          yes)
-                CFLAGS="$CFLAGS -O3";
-                CXXFLAGS="$CXXFLAGS -O3";
-          ;;
-          no) ;;
-          *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-optimize" >&5
-echo "$as_me: error: bad value ${enableval} for --enable-optimize" >&2;}
-   { (exit 1); exit 1; }; } ;;
-          esac
+{ echo "$as_me:$LINENO: checking whether to enable maintainer-specific portions of Makefiles" >&5
+echo $ECHO_N "checking whether to enable maintainer-specific portions of Makefiles... $ECHO_C" >&6; }
+    # Check whether --enable-maintainer-mode was given.
+if test "${enable_maintainer_mode+set}" = set; then
+  enableval=$enable_maintainer_mode; USE_MAINTAINER_MODE=$enableval
 else
-   optimize=false
+  USE_MAINTAINER_MODE=no
 fi
+
+  { echo "$as_me:$LINENO: result: $USE_MAINTAINER_MODE" >&5
+echo "${ECHO_T}$USE_MAINTAINER_MODE" >&6; }
+   if test $USE_MAINTAINER_MODE = yes; then
+  MAINTAINER_MODE_TRUE=
+  MAINTAINER_MODE_FALSE='#'
+else
+  MAINTAINER_MODE_TRUE='#'
+  MAINTAINER_MODE_FALSE=
+fi
+
+  MAINT=$MAINTAINER_MODE_TRUE
+
 
 
 # set debug info flag if no optimization flags are set.
@@ -6652,6 +6659,13 @@ LIBOBJS=$ac_libobjs
 LTLIBOBJS=$ac_ltlibobjs
 
 
+if test -z "${MAINTAINER_MODE_TRUE}" && test -z "${MAINTAINER_MODE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"MAINTAINER_MODE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"MAINTAINER_MODE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -7313,6 +7327,9 @@ am__leading_dot!$am__leading_dot$ac_delim
 AMTAR!$AMTAR$ac_delim
 am__tar!$am__tar$ac_delim
 am__untar!$am__untar$ac_delim
+MAINTAINER_MODE_TRUE!$MAINTAINER_MODE_TRUE$ac_delim
+MAINTAINER_MODE_FALSE!$MAINTAINER_MODE_FALSE$ac_delim
+MAINT!$MAINT$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
 LDFLAGS!$LDFLAGS$ac_delim
@@ -7340,9 +7357,6 @@ LIBGCRYPT_CFLAGS!$LIBGCRYPT_CFLAGS$ac_delim
 LIBGCRYPT_LIBS!$LIBGCRYPT_LIBS$ac_delim
 HAVE_GCRYPT_TRUE!$HAVE_GCRYPT_TRUE$ac_delim
 HAVE_GCRYPT_FALSE!$HAVE_GCRYPT_FALSE$ac_delim
-LIBMCRYPT_CONFIG!$LIBMCRYPT_CONFIG$ac_delim
-LIBMCRYPT_CFLAGS!$LIBMCRYPT_CFLAGS$ac_delim
-LIBMCRYPT_LIBS!$LIBMCRYPT_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -7384,6 +7398,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+LIBMCRYPT_CONFIG!$LIBMCRYPT_CONFIG$ac_delim
+LIBMCRYPT_CFLAGS!$LIBMCRYPT_CFLAGS$ac_delim
+LIBMCRYPT_LIBS!$LIBMCRYPT_LIBS$ac_delim
 HAVE_MCRYPT_TRUE!$HAVE_MCRYPT_TRUE$ac_delim
 HAVE_MCRYPT_FALSE!$HAVE_MCRYPT_FALSE$ac_delim
 BOTAN_CONFIG!$BOTAN_CONFIG$ac_delim
@@ -7419,7 +7436,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 33; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 36; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -7902,7 +7919,7 @@ NOT available:
 
    $NOT_LIBS
 
-Use \"make run_all\" in src/ to run all built binaries.
+Use \"make runall\" in src/ to run all built binaries.
 " >&5
 echo "$as_me:
 
@@ -7914,5 +7931,5 @@ NOT available:
 
    $NOT_LIBS
 
-Use \"make run_all\" in src/ to run all built binaries.
+Use \"make runall\" in src/ to run all built binaries.
 " >&6;}
