Adding verify.cpp which tests different implementations of the same cipher against each other. Also testing Crypto++ now.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -675,6 +675,14 @@ LIBMCRYPT_LIBS
 BOTAN_CONFIG
 BOTAN_CFLAGS
 BOTAN_LIBS
+CRYPTO_PP_PREFIX
+CRYPTO_PP_VERSION_STRING
+CRYPTO_PP_VERSION_NUMBER
+CRYPTO_PP_STYLE
+CRYPTO_PP_LIB_NAME
+CRYPTO_PP_INCLUDE_PREFIX
+CRYPTO_PP_CXXFLAGS
+CRYPTO_PP_LDFLAGS
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1280,6 +1288,8 @@ Optional Packages:
   --with-libmcrypt-prefix=PFX   Prefix where libmcrypt is installed (optional)
   --with-botan-prefix=PFX       Prefix where botan is installed (optional)
   --with-botan-exec-prefix=PFX Exec prefix where botan is installed (optional)
+  --with-crypto-prefix=PREFIX
+                          prefix where crypto++ is installed
 
 Some influential environment variables:
   CC          C compiler command
@@ -2297,8 +2307,8 @@ am__tar='${AMTAR} chof - "$$tardir"'; am__untar='${AMTAR} xf -'
 if test "${enable_optimize+set}" = set; then
   enableval=$enable_optimize;  case "${enableval}" in
           yes)
-                CFLAGS="$CFLAGS -O3 -DNDEBUG";
-                CXXFLAGS="$CXXFLAGS -O3 -DNDEBUG";
+                CFLAGS="$CFLAGS -O3";
+                CXXFLAGS="$CXXFLAGS -O3";
           ;;
           no) ;;
           *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-optimize" >&5
@@ -4608,6 +4618,168 @@ echo "$as_me: error:
 
 
 
+
+
+
+
+
+
+
+
+# Check whether --with-crypto-prefix was given.
+if test "${with_crypto_prefix+set}" = set; then
+  withval=$with_crypto_prefix; CRYPTO_PP_PREFIX="$withval"
+else
+  CRYPTO_PP_PREFIX=""
+fi
+
+
+
+
+min_crypto_version=5.5
+{ echo "$as_me:$LINENO: checking for crypto++ version >= $min_crypto_version" >&5
+echo $ECHO_N "checking for crypto++ version >= $min_crypto_version... $ECHO_C" >&6; }
+
+crypto_pp_file_with_version="cryptlib.h"
+
+CRYPTO_PP_STYLE="unknown"
+CRYPTO_PP_LIB_NAME="unknown"
+crypto_pp_include_i="unknown"
+CRYPTO_PP_INCLUDE_PREFIX="unknown"
+CRYPTO_PP_DEFINE="unknown"
+CRYPTO_PP_LIB="unknown"
+
+#
+# Set CRYPTO_PP_PREFIX if the user has not set it in the configure command line
+# We don't use AC_CHECK_FILE to avoid caching.
+#
+if test x$CRYPTO_PP_PREFIX = x ; then
+	CRYPTO_PP_PREFIX="/usr"
+fi
+
+#
+# Find the Cryptopp header
+#
+if test -f $CRYPTO_PP_PREFIX/$crypto_pp_file_with_version; then
+	CRYPTO_PP_STYLE="sources"
+	CRYPTO_PP_LIB_NAME="cryptopp"
+	crypto_pp_include_i="$CRYPTO_PP_PREFIX"
+	CRYPTO_PP_INCLUDE_PREFIX="."
+	CRYPTO_PP_DEFINE="__CRYPTO_SOURCE__"
+	CRYPTO_PP_LIB="$CRYPTO_PP_PREFIX"
+	{ { echo "$as_me:$LINENO: error:
+	Specifying the cryptopp source files directory for \"--with-crypto-prefix=\"
+	will not work because cryptopp uses headers with the same name of system
+	headers (e.g. zlib.h) and you must be able to distinguish the system
+	headers from cryptopp headers in an #include directive.
+	Please run \"PREFIX=/home/YourUserName/usr/cryptopp make install\" on
+	the cryptopp directory to properly install cryptopp in your system." >&5
+echo "$as_me: error:
+	Specifying the cryptopp source files directory for \"--with-crypto-prefix=\"
+	will not work because cryptopp uses headers with the same name of system
+	headers (e.g. zlib.h) and you must be able to distinguish the system
+	headers from cryptopp headers in an #include directive.
+	Please run \"PREFIX=/home/YourUserName/usr/cryptopp make install\" on
+	the cryptopp directory to properly install cryptopp in your system." >&2;}
+   { (exit 1); exit 1; }; }
+elif test -f $CRYPTO_PP_PREFIX/include/cryptopp/$crypto_pp_file_with_version; then
+	CRYPTO_PP_STYLE="installed"
+	CRYPTO_PP_LIB_NAME="cryptopp"
+	crypto_pp_include_i="$CRYPTO_PP_PREFIX/include"
+	CRYPTO_PP_INCLUDE_PREFIX="$CRYPTO_PP_LIB_NAME"
+	CRYPTO_PP_DEFINE="__CRYPTO_INSTALLED__"
+	CRYPTO_PP_LIB="$CRYPTO_PP_PREFIX/lib"
+elif test -f $CRYPTO_PP_PREFIX/include/crypto++/$crypto_pp_file_with_version; then
+       	# Debian uses libcrypto++5.1 - it's not my fault, please soda patch the package
+	CRYPTO_PP_STYLE="gentoo_debian"
+	CRYPTO_PP_LIB_NAME="crypto++"
+	crypto_pp_include_i="$CRYPTO_PP_PREFIX/include"
+	CRYPTO_PP_INCLUDE_PREFIX="$CRYPTO_PP_LIB_NAME"
+	CRYPTO_PP_DEFINE="__CRYPTO_SOURCE__"
+	CRYPTO_PP_LIB="$CRYPTO_PP_PREFIX/lib"
+fi
+
+#
+# Check for success in finding cryptopp
+#
+if test $CRYPTO_PP_STYLE = "unknown"; then
+	#
+	# If the execution reaches here, we have failed.
+	#
+	{ { echo "$as_me:$LINENO: error:
+	Could not find cryptopp header file \"$crypto_pp_file_with_version\".
+	Please check if the path \"$CRYPTO_PP_PREFIX\" is valid." >&5
+echo "$as_me: error:
+	Could not find cryptopp header file \"$crypto_pp_file_with_version\".
+	Please check if the path \"$CRYPTO_PP_PREFIX\" is valid." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+#
+# Find out the cryptopp version and check against the minimum required
+#
+crypto_pp_include_dir="$crypto_pp_include_i/$CRYPTO_PP_INCLUDE_PREFIX"
+crypto_pp_header_path="$crypto_pp_include_dir/$crypto_pp_file_with_version"
+
+CRYPTO_PP_VERSION_STRING=$(grep "Reference Manual" $crypto_pp_header_path | \
+	sed -e 's/[^0-9]*\([0-9.]*\).*/\1/')
+
+CRYPTO_PP_VERSION_NUMBER=$(echo $CRYPTO_PP_VERSION_STRING | \
+	$AWK 'BEGIN { FS = "."; } { printf "%d", ($1 * 1000 + $2) * 1000 + $3;}')
+
+minvers=$(echo $min_crypto_version | \
+	$AWK 'BEGIN { FS = "."; } { printf "%d", ($1 * 1000 + $2) * 1000 + $3;}')
+
+if test -n "$CRYPTO_PP_VERSION_NUMBER" && test "$CRYPTO_PP_VERSION_NUMBER" -ge $minvers; then
+	result="yes (version $CRYPTO_PP_VERSION_STRING, $CRYPTO_PP_STYLE)"
+else
+	result="no"
+fi
+{ echo "$as_me:$LINENO: result: $result" >&5
+echo "${ECHO_T}$result" >&6; }
+
+#
+# FLAGS
+#
+CRYPTO_PP_CXXFLAGS="-isystem $crypto_pp_include_i -D$CRYPTO_PP_DEFINE"
+CRYPTO_PP_LDFLAGS="-L$CRYPTO_PP_LIB"
+
+
+cat >>confdefs.h <<_ACEOF
+#define CRYPTOPP_INCLUDE_PREFIX $CRYPTO_PP_INCLUDE_PREFIX
+_ACEOF
+
+
+#
+# Exported symbols
+#
+
+
+
+
+
+
+
+
+
+
+{ echo "$as_me:$LINENO: Crypto++ version number is $CRYPTO_PP_VERSION_NUMBER" >&5
+echo "$as_me: Crypto++ version number is $CRYPTO_PP_VERSION_NUMBER" >&6;}
+
+
+case "$CRYPTO_PP_STYLE" in
+    gentoo_debian | installed | sources)
+	;;
+    *) { { echo "$as_me:$LINENO: error:
+*** Could not find a suitable version of the Crypto++ library! ***
+*** Install the libbotan-dev package or use the source from http://www.cryptopp.com ***" >&5
+echo "$as_me: error:
+*** Could not find a suitable version of the Crypto++ library! ***
+*** Install the libbotan-dev package or use the source from http://www.cryptopp.com ***" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+esac
+
 # Output Makefiles
 
 ac_config_files="$ac_config_files Makefile src/Makefile"
@@ -5414,11 +5586,19 @@ ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
 BOTAN_LIBS!$BOTAN_LIBS$ac_delim
+CRYPTO_PP_PREFIX!$CRYPTO_PP_PREFIX$ac_delim
+CRYPTO_PP_VERSION_STRING!$CRYPTO_PP_VERSION_STRING$ac_delim
+CRYPTO_PP_VERSION_NUMBER!$CRYPTO_PP_VERSION_NUMBER$ac_delim
+CRYPTO_PP_STYLE!$CRYPTO_PP_STYLE$ac_delim
+CRYPTO_PP_LIB_NAME!$CRYPTO_PP_LIB_NAME$ac_delim
+CRYPTO_PP_INCLUDE_PREFIX!$CRYPTO_PP_INCLUDE_PREFIX$ac_delim
+CRYPTO_PP_CXXFLAGS!$CRYPTO_PP_CXXFLAGS$ac_delim
+CRYPTO_PP_LDFLAGS!$CRYPTO_PP_LDFLAGS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 3; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 11; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
