Implementing speed tests for Botan library.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -672,6 +672,9 @@ LIBGCRYPT_LIBS
 LIBMCRYPT_CONFIG
 LIBMCRYPT_CFLAGS
 LIBMCRYPT_LIBS
+BOTAN_CONFIG
+BOTAN_CFLAGS
+BOTAN_LIBS
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1275,6 +1278,8 @@ Optional Packages:
   --with-libgcrypt-prefix=PFX
                           prefix where LIBGCRYPT is installed (optional)
   --with-libmcrypt-prefix=PFX   Prefix where libmcrypt is installed (optional)
+  --with-botan-prefix=PFX       Prefix where botan is installed (optional)
+  --with-botan-exec-prefix=PFX Exec prefix where botan is installed (optional)
 
 Some influential environment variables:
   CC          C compiler command
@@ -4444,6 +4449,165 @@ echo "$as_me: error:
 
 
 
+
+
+# Check whether --with-botan-prefix was given.
+if test "${with_botan_prefix+set}" = set; then
+  withval=$with_botan_prefix; botan_config_prefix="$withval"
+else
+  botan_config_prefix=""
+fi
+
+
+# Check whether --with-botan-exec-prefix was given.
+if test "${with_botan_exec_prefix+set}" = set; then
+  withval=$with_botan_exec_prefix; botan_config_exec_prefix="$withval"
+else
+  botan_config_exec_prefix=""
+fi
+
+
+  if test x$botan_config_exec_prefix != x ; then
+     botan_config_args="$botan_config_args --exec-prefix=$botan_config_exec_prefix"
+     if test x${BOTAN_CONFIG+set} != xset ; then
+       BOTAN_CONFIG=$botan_config_exec_prefix/bin/botan-config
+     fi
+  fi
+  if test x$botan_config_prefix != x ; then
+     botan_config_args="$botan_config_args --prefix=$botan_config_prefix"
+     if test x${BOTAN_CONFIG+set} != xset ; then
+       BOTAN_CONFIG=$botan_config_prefix/bin/botan-config
+     fi
+  fi
+
+  # Extract the first word of "botan-config", so it can be a program name with args.
+set dummy botan-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_BOTAN_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $BOTAN_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_BOTAN_CONFIG="$BOTAN_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_BOTAN_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_BOTAN_CONFIG" && ac_cv_path_BOTAN_CONFIG="no"
+  ;;
+esac
+fi
+BOTAN_CONFIG=$ac_cv_path_BOTAN_CONFIG
+if test -n "$BOTAN_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $BOTAN_CONFIG" >&5
+echo "${ECHO_T}$BOTAN_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  { echo "$as_me:$LINENO: checking for botan - version >= 1.6.1" >&5
+echo $ECHO_N "checking for botan - version >= 1.6.1... $ECHO_C" >&6; }
+
+  no_botan=""
+  if test "$BOTAN_CONFIG" = "no" ; then
+     no_botan=yes
+  else
+     BOTAN_CFLAGS="`$BOTAN_CONFIG $botan_config_args --cflags`"
+     BOTAN_LIBS="`$BOTAN_CONFIG $botan_config_args --libs`"
+
+        botan_config_major_version=`$BOTAN_CONFIG $botan_config_args \
+         --version | sed 's/[^0-9]*\([0-9]*\).\([0-9]*\).\([0-9]*\)/\1/'`
+        botan_config_minor_version=`$BOTAN_CONFIG $botan_config_args \
+         --version | sed 's/[^0-9]*\([0-9]*\).\([0-9]*\).\([0-9]*\)/\2/'`
+        botan_config_micro_version=`$BOTAN_CONFIG $botan_config_args \
+         --version | sed 's/[^0-9]*\([0-9]*\).\([0-9]*\).\([0-9]*\)/\3/'`
+        botan_wanted_major_version="1"
+        botan_wanted_minor_version="6"
+        botan_wanted_micro_version="1"
+
+        # Compare wanted version to what config script returned.
+        # If I knew what library was being run, i'd probably also compile
+        # a test program at this point (which also extracted and tested
+        # the version in some library-specific way)
+        if test "$botan_config_major_version" -lt \
+                        "$botan_wanted_major_version" \
+          -o \( "$botan_config_major_version" -eq \
+                        "$botan_wanted_major_version" \
+            -a "$botan_config_minor_version" -lt \
+                        "$botan_wanted_minor_version" \) \
+          -o \( "$botan_config_major_version" -eq \
+                        "$botan_wanted_major_version" \
+            -a "$botan_config_minor_version" -eq \
+                        "$botan_wanted_minor_version" \
+            -a "$botan_config_micro_version" -lt \
+                        "$botan_wanted_micro_version" \) ; then
+          # older version found
+          no_botan=yes
+          echo -n "*** An old version of botan "
+          echo -n "($botan_config_major_version"
+          echo -n ".$botan_config_minor_version"
+          echo    ".$botan_config_micro_version) was found."
+          echo -n "*** You need a version of botan newer than "
+          echo -n "$botan_wanted_major_version"
+          echo -n ".$botan_wanted_minor_version"
+          echo    ".$botan_wanted_micro_version."
+          echo "***"
+          echo "*** If you have already installed a sufficiently new version, this error"
+          echo "*** probably means that the wrong copy of the botan-config shell script is"
+          echo "*** being found. The easiest way to fix this is to remove the old version"
+          echo "*** of botan, but you can also set the BOTAN_CONFIG environment to point to the"
+          echo "*** correct copy of botan-config. (In this case, you will have to"
+          echo "*** modify your LD_LIBRARY_PATH environment variable, or edit /etc/ld.so.conf"
+          echo "*** so that the correct libraries are found at run-time)"
+        fi
+
+  fi
+  if test "x$no_botan" = x ; then
+     { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+     :
+  else
+     { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+     if test "$BOTAN_CONFIG" = "no" ; then
+       echo "*** The botan-config script installed by botan could not be found"
+       echo "*** If botan was installed in PREFIX, make sure PREFIX/bin is in"
+       echo "*** your path, or set the BOTAN_CONFIG environment variable to the"
+       echo "*** full path to botan-config."
+     fi
+     BOTAN_CFLAGS=""
+     BOTAN_LIBS=""
+     { { echo "$as_me:$LINENO: error:
+*** Could not find a suitable version of the Botan library! ***
+*** Install the libbotan-dev package or use the source from http://botan.randombit.net ***" >&5
+echo "$as_me: error:
+*** Could not find a suitable version of the Botan library! ***
+*** Install the libbotan-dev package or use the source from http://botan.randombit.net ***" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
+
+
+
+
+
 # Output Makefiles
 
 ac_config_files="$ac_config_files Makefile src/Makefile"
@@ -5206,8 +5370,8 @@ LIBGCRYPT_LIBS!$LIBGCRYPT_LIBS$ac_delim
 LIBMCRYPT_CONFIG!$LIBMCRYPT_CONFIG$ac_delim
 LIBMCRYPT_CFLAGS!$LIBMCRYPT_CFLAGS$ac_delim
 LIBMCRYPT_LIBS!$LIBMCRYPT_LIBS$ac_delim
-LIBOBJS!$LIBOBJS$ac_delim
-LTLIBOBJS!$LTLIBOBJS$ac_delim
+BOTAN_CONFIG!$BOTAN_CONFIG$ac_delim
+BOTAN_CFLAGS!$BOTAN_CFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -5242,6 +5406,52 @@ N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
 ' >>$CONFIG_STATUS <conf$$subs.sed
 rm -f conf$$subs.sed
 cat >>$CONFIG_STATUS <<_ACEOF
+CEOF$ac_eof
+_ACEOF
+
+
+ac_delim='%!_!# '
+for ac_last_try in false false false false false :; do
+  cat >conf$$subs.sed <<_ACEOF
+BOTAN_LIBS!$BOTAN_LIBS$ac_delim
+LIBOBJS!$LIBOBJS$ac_delim
+LTLIBOBJS!$LTLIBOBJS$ac_delim
+_ACEOF
+
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 3; then
+    break
+  elif $ac_last_try; then
+    { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
+echo "$as_me: error: could not make $CONFIG_STATUS" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    ac_delim="$ac_delim!$ac_delim _$ac_delim!! "
+  fi
+done
+
+ac_eof=`sed -n '/^CEOF[0-9]*$/s/CEOF/0/p' conf$$subs.sed`
+if test -n "$ac_eof"; then
+  ac_eof=`echo "$ac_eof" | sort -nru | sed 1q`
+  ac_eof=`expr $ac_eof + 1`
+fi
+
+cat >>$CONFIG_STATUS <<_ACEOF
+cat >"\$tmp/subs-2.sed" <<\CEOF$ac_eof
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
+_ACEOF
+sed '
+s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
+s/^/s,@/; s/!/@,|#_!!_#|/
+:n
+t n
+s/'"$ac_delim"'$/,g/; t
+s/$/\\/; p
+N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
+' >>$CONFIG_STATUS <conf$$subs.sed
+rm -f conf$$subs.sed
+cat >>$CONFIG_STATUS <<_ACEOF
+:end
+s/|#_!!_#|//g
 CEOF$ac_eof
 _ACEOF
 
@@ -5495,7 +5705,7 @@ s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
 s&@MKDIR_P@&$ac_MKDIR_P&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed 's/|#_!!_#|//g' >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
